### ISSUE TITLE
MQTT not appearing

### ISSUE THREAD

**Issue by patrol420** [xoseperez/espurna#1457]
* *Arduino Core version*
* *ESPurna version* 1.13.3
* *Flash mode* dout
* *Device brand, model and version* generic lightbulb tw3eys wifi chip with esp8266

**Tools used**
win10 and ide 1.8.7

ive flashed 1 of these already and everything was seemless. this one i cannot seem to get the MQTT option to appear in web menu. ive probly built it 20 times trying different things in hardware.h for mqtt support. but nothing works. output on seriel on startup says 
[000674] [MQTT] Async ENABLED, SSL DISABLED, Autoconnect ENABLED
[000687] [THINGSPEAK] Async ENABLED, SSL DISABLED
seems to be on but not appearing. any ideas

**Comment by xoseperez** [comment]
Maybe a problem in the web image? Are there any javascript errors in the browser?

**Comment by patrol420** [comment]
doesnt seem to be, if i flash the latest bin for lc02 i get every option in the menu... im i correct in thinking that if i was to compile the latest source with the hardware selected i should have mqtt default. i remove // before mqtt support in arduino.h and still same thing.

**Comment by xoseperez** [comment]
MQTT is enabled by default in all builds. So you should have this. You can also check if you are receiving a `mqttVisible` key via web sockets on the browser (using the network inspector).

**Comment by kakaki** [comment]
I have similar problem with Schedule, ntp and Sensors menus - they are not showing - got 2 identical BW-SHP2 - one is on 1.13.1 - working fine with all options visible in menu, other was upgraded to 1.13.3.
In web sockets there is no info to set ntpVisible, shdVisible and sensorsVisible.

Same problem is on other devices updated to 1.13.3.

![zrzut ekranu 2018-12-28 o 19 40 49](https://user-images.githubusercontent.com/156115/50524956-f4ee9180-0ad8-11e9-83e6-d5e4fe1ac339.png)
![zrzut ekranu 2018-12-28 o 19 41 04](https://user-images.githubusercontent.com/156115/50524958-f8821880-0ad8-11e9-97ef-5469cba1dd0d.png)

**Comment by patrol420** [comment]
> I have similar problem with Schedule, ntp and Sensors menus - they are not showing - got 2 identical BW-SHP2 - one is on 1.13.1 - working fine with all options visible in menu, other was upgraded to 1.13.3.
> In web sockets there is no info to set ntpVisible, shdVisible and sensorsVisible.
> 
> Same problem is on other devices updated to 1.13.3.
> 
> ![zrzut ekranu 2018-12-28 o 19 40 49](https://user-images.githubusercontent.com/156115/50524956-f4ee9180-0ad8-11e9-83e6-d5e4fe1ac339.png)
> ![zrzut ekranu 2018-12-28 o 19 41 04](https://user-images.githubusercontent.com/156115/50524958-f8821880-0ad8-11e9-97ef-5469cba1dd0d.png)

going off what you said, i just flashed 1.13.1 and it works perfect first go. dam i spent 4 hours on it yesterday just flashing it, shes held up to atleast 100 flashs lol

**Comment by mcspr** [comment]
What lwip version are you using (v1, v2, low memory, high bandwidth)? Assuming it is self-built from "win10 and ide 1.8.7"
Can you check with [this version](https://github.com/me-no-dev/ESPAsyncWebServer/archive/4c621f340c731d621e21fef4d32928f4bec61b85.zip) of ESPAsyncWebServer lib?
Or [this](https://github.com/me-no-dev/ESPAsyncWebServer/archive/313f3372c61f6f4bff9c157f02a07ba912d3d4d9.zip), basing on platformio.ini pinned version. Only needed if using webui on iOS

**Comment by kakaki** [comment]
Thanks, it helps, was using version 1.2.0 from git - it's never then version in archive, add's message eques.
https://github.com/me-no-dev/ESPAsyncWebServer/commit/bed4146ec647fd1cdfd1d2485724369c92cab8e6

**Comment by reaper7** [comment]
I have the same issue with unvisible menus for mqtt, shedule, ntp...
arduino 1.8.7, win10, lwip high bandwidth

espurna from master branch (1.13.3) works OK
espurna from dev branch (1.13.4-dev) works but **without** mqtt,schedule,ntp in webmenu

I don't change any external libs, only espurna versions

**Comment by xoseperez** [comment]
Can you build the web interface images using `gulp` command? Check this wiki page: https://github.com/xoseperez/espurna/wiki/WebInterface

**Comment by xoseperez** [comment]
I have rebuilt and commit the webUI images, maybe you can also do a `git pull`, rebuild and flash.

**Comment by mcspr** [comment]
> arduino 1.8.7, **win10**, lwip high bandwidth, **ESPAsyncWebServer current git version**

my bet it is related to #1300. current git of espasyncwebserver limits the buffer of sent ws messages by 8. that buffer is kept until the client receives them and windows is inherently slow at that.
+ as confirmed by @kakaki, rolling back a version helps

there is a workaround by doing request-response for module configuration, that way client will send N config requests and receive N config responses back, bu i have not tried it with lwip1 builds.

**Comment by reaper7** [comment]
@mcspr - I have not tried the older version of espasyncwebserver yet
because I use the latest version in several other projects.
 
I build 1.13.3(working) and 1.13.4-dev(not working) with the same espasyncwebserver(current master version),
so ... something has changed inside espurna when it comes to using a web server.

**Comment by mcspr** [comment]
@patrol420 Thank you for providing config!

As to difference between 1.13.3 and 1.13.4-dev:
If you are using Chrome, you can check web inspector to see that it sends exactly 9 ws messages on 1.13.3. Which fits in above limit, because first is acked immediately while 8 are still queued.
1.13.4-dev revamps relay config to send more ws messages, which results in 12 messages that no longer fit the queue fully.
And this could be safely mitigated by not using latest commit to the master of ESPAsyncWebServer. Queue limit added seems arbitrary, as it based on amount of messages and not their size, and can safely be avoided here.

I think i am going to do the proposed workaround to avoid possible issues like this (+ there would be nicer api to fetch module config after the initial one)

**Comment by reaper7** [comment]
@mcspr - thanks for explaining :)
I'm new espurna user, I did not know this repo deeply yet. (compared to tasmota, it's damn fast, I'm going to stay with this project)

You understand that I would like to have and use one version of the external library like ESPAsyncWebServer for all "my" projects.
so...every possible improvement will be appreciated.

**Comment by daxkamala** [comment]
Hooray! And thanks for the pointers.
I just changed line 30 in AsyncWebSocket.h (#define WS_MAX_QUEUED_MESSAGES) from 8 to 16 and all the menus returned.
This file will be under your libraries, ESPAsyncWebServer-Master in my case.
Everything else seems to work fine now.

**Comment by reaper7** [comment]
@daxkamala - I checked and it works :)

**Comment by mcspr** [comment]
@reaper7 @daxkamala can you verify changes in #1387 ? 
without modifying WS_MAX_QUEUED_MESSAGES value of ESPAsyncWebServer

pre-built webui headers (replace `code\espurna\static\*.h`):
[webui.zip](https://github.com/xoseperez/espurna/files/2887540/webui.zip)

**Comment by reaper7** [comment]
@mcspr - not yet, I will try during the weekend. (if arduino will reconcile with python ;) )

**Comment by mcspr** [comment]
@reaper7 two options:
1. https://help.github.com/articles/checking-out-pull-requests-locally/
2. slightly more involved. in the espurna git repo directory:
```
$ git remote add mcspr https://github.com/mcspr/espurna
$ git fetch mcspr compact-ws
$ git checkout -b compact-ws mcspr/compact-ws
```
or, if you do not want to modify your files, instead of checkout:
```
$ git worktree add -b compact-ws compact-ws mcspr/compact-ws
# compact-ws/ directory will now contain files from PR
```

**Comment by reaper7** [comment]
@mcspr - looks wery well!
for me almost everything works as it should...
with one small exception -> SWITCHES (SONOFF T1 (3) )
Switches bookmark shows 11 switches, without numbers:
![schowek01](https://user-images.githubusercontent.com/4134851/53198739-79631980-361d-11e9-8d86-9ce423c1368e.jpg)

I always use the same custom config:
```
/*
my devices:
0 sonoff rf bridge  192.168.0.150
1 sonoff t1 3ch     192.168.0.151
2 sonoff t1 3ch     192.168.0.152
3 sonoff t1 3ch     192.168.0.153
4 sonoff t1 3ch     192.168.0.154
5 sonoff t1 3ch     192.168.0.155
6 sonoff rf         192.168.0.156
7 sonoff rf         192.168.0.157
8 sonoff s20        192.168.0.158
9 sonoff s20        192.168.0.159
*/

#define SEL_DEVICE 1

#if SEL_DEVICE == 0
  #define ITEAD_SONOFF_RFBRIDGE
  #define MY_ROOM                     "salon"
  #define MY_HOSTNAME                 "sonoffbr150"
  #define RELAY_BOOT_MODE             0                                         // 0 - off, 1 - on, 2 - same
  #define LED1_MODE                   LED_MODE_RELAY
  #define WIFI1_IP                    "192.168.0.150"
#elif SEL_DEVICE == 1
  #define ITEAD_SONOFF_T1_3CH
  #define MY_ROOM                     "salon"
  #define MY_HOSTNAME                 "sonofft13151"
  #define RELAY_BOOT_MODE             2                                         // 0 - off, 1 - on, 2 - same
  #define LED1_MODE                   LED_MODE_FINDME
  #define WIFI1_IP                    "192.168.0.151"
#elif SEL_DEVICE == 6
  #define ITEAD_SONOFF_RF
  #define MY_ROOM                     "salon"
  #define MY_HOSTNAME                 "sonoffrf156"
  #define RELAY_BOOT_MODE             2                                         // 0 - off, 1 - on, 2 - same
  #define LED1_MODE                   LED_MODE_FINDME
  #define WIFI1_IP                    "192.168.0.156"
#elif SEL_DEVICE == 7
  #define ITEAD_SONOFF_RF
  #define MY_ROOM                     "salon"
  #define MY_HOSTNAME                 "sonoffrf157"
  #define RELAY_BOOT_MODE             2                                         // 0 - off, 1 - on, 2 - same
  #define LED1_MODE                   LED_MODE_FINDME
  #define WIFI1_IP                    "192.168.0.157"
#elif SEL_DEVICE == 8
  #define ITEAD_S20
  #define MY_ROOM                     "salon"
  #define MY_HOSTNAME                 "sonoffs20158"
  #define RELAY_BOOT_MODE             2                                         // 0 - off, 1 - on, 2 - same
//  #define LED1_MODE                   LED_MODE_FINDME
  #define LED1_MODE                   LED_MODE_MQTT
  #define WIFI1_IP                    "192.168.0.158"
#elif SEL_DEVICE == 9
  #define ITEAD_S20
  #define MY_ROOM                     "salon"
  #define MY_HOSTNAME                 "sonoffs20159"
  #define RELAY_BOOT_MODE             2                                         // 0 - off, 1 - on, 2 - same
//  #define LED1_MODE                   LED_MODE_FINDME
  #define LED1_MODE                   LED_MODE_MQTT
  #define WIFI1_IP                    "192.168.0.159"
#elif SEL_DEVICE == 99
//  #define ARILUX_AL_LC11
//  #define ITEAD_SONOFF_IFAN02
//  #define ITEAD_BNSZ01
  #define ITEAD_SONOFF_TH
  #define MY_ROOM                     "salon"
  #define MY_HOSTNAME                 "espurnatest"
  #define RELAY_BOOT_MODE             2                                         // 0 - off, 1 - on, 2 - same
//  #define LED1_MODE                   LED_MODE_FINDME
  #define LED1_MODE                   LED_MODE_MQTT
  #define WIFI1_IP                    "192.168.0.199"
  
//  #define LIGHT_USE_RGB               1
//  #define LIGHT_USE_GAMMA             1
  #define LIGHT_USE_WHITE             1
  #define LIGHT_USE_CCT               1
#else
  #define ESPURNA_CORE
#endif

#define WIFI1_SSID                  "SomeSSID"
#define WIFI1_PASS                  "SomePASS"
#define WIFI2_SSID                  WIFI1_SSID
#define WIFI2_PASS                  WIFI1_PASS

#if defined(WIFI1_IP)
  #define WIFI1_GW                  "192.168.0.254"
  #define WIFI1_MASK                "255.255.255.0"
  #define WIFI1_DNS                 "192.168.0.254"
  #define WIFI2_IP                  WIFI1_IP
  #define WIFI2_GW                  WIFI1_GW
  #define WIFI2_MASK                WIFI1_MASK
  #define WIFI2_DNS                 WIFI1_DNS
#endif

#define ADMIN_PASS                  "SomeAdminPass"                                  // Default password (WEB, OTA, WIFI SoftAP)

#if defined(ESPURNA_CORE)

  #define WIFI_FALLBACK_APMODE        1                                         // Fallback to AP mode if no STA connection
  #define USE_PASSWORD                1

#else

  #define MY_HOME "myhome"

  #if defined(MY_ROOM) && defined(MY_HOSTNAME)
    #define HOSTNAME                    MY_HOSTNAME
    #define MQTT_TOPIC                  MY_HOME "/" MY_ROOM "/" MY_HOSTNAME "/"
  #else
    #define MQTT_TOPIC                  MY_HOME "/"
  #endif

  #define WIFI_FALLBACK_APMODE        0                                         // Fallback to AP mode if no STA connection
  #define USE_PASSWORD                0

  #define TELNET_SUPPORT              0                                         // Enable telnet support by default (3.34Kb)
  #define TERMINAL_SUPPORT            0                                         // Enable terminal commands (0.97Kb)

  #define WEB_SUPPORT                 1                                         // Enable web support (http, api, 121.65Kb)
  #define WEB_EMBEDDED                1                                         // Build the firmware with the web interface embedded in
  #define WEB_FORCE_PASS_CHANGE       0

  #define DEBUG_SERIAL_SUPPORT        0                                         // Enable serial debug log
  #define DEBUG_UDP_SUPPORT           0                                         // Enable UDP debug log
  #define DEBUG_TELNET_SUPPORT        0                                         // Enable telnet debug log (will only work if TELNET_SUPPORT is also 1)
  #define DEBUG_WEB_SUPPORT           0                                         // Enable web debug log (will only work if WEB_SUPPORT is also 1)

  #undef NTP_SUPPORT
  #define NTP_SUPPORT                 1                                         // Build with NTP support by default (6.78Kb)
  #define NTP_SERVER                  "myhome.lan"

  #undef MQTT_SUPPORT
  #define MQTT_SUPPORT                1                                         // MQTT support (22.38Kb async, 12.48Kb sync)
  #undef MQTT_ENABLED
  #define MQTT_ENABLED                1                                         // Do not enable MQTT connection by default
  #define MQTT_AUTOCONNECT            1                                         // If enabled and MDNS_SERVER_SUPPORT=1 will perform an autodiscover and
  #define MQTT_SERVER                 "rpi"                                     // Default MQTT broker address
  #define MQTT_USER                   "mqttuser"                              // Default MQTT broker usename
  #define MQTT_PASS                   "mqttpass"                              // Default MQTT broker password
  #define MQTT_RETAIN                 true                                      // MQTT retain flag
  #define MQTT_QOS                    0                                         // MQTT QoS value for all messages
  #define MQTT_USE_JSON               0                                         // Group messages in a JSON body

  #define HOMEASSISTANT_SUPPORT       1                                         // Build with home assistant support (if MQTT, 1.64Kb)
  #define HOMEASSISTANT_ENABLED       1                                         // Integration not enabled by default
  #define HOMEASSISTANT_PREFIX        MY_HOME                                   // Default MQTT prefix

  #define DOMOTICZ_SUPPORT            0                                         // Build with domoticz (if MQTT) support (1.72Kb)
  #define THINGSPEAK_SUPPORT          0                                         // Enable Thingspeak support by default (2.56Kb)
  #define ALEXA_SUPPORT               0                                         // Enable Alexa support by default (10.84Kb)

#endif
```

**Comment by xoseperez** [comment]
Just merged #1387 which solves this issue within ESPurna. Anyway it will be interesting to have some different approach to this on AsyncWebSocket class...

**Comment by mcspr** [comment]
@reaper7 i think you were missing correct webui. courtesy of Xose, `dev` now has prebuilt ones, so just `git pull` will do. i do not see the bug you describing rn with a test device

**Comment by xoseperez** [comment]
Yes, I think web UI images should be created for every new feature committed. It's not obvious you have to build them too otherwise.

**Comment by reaper7** [comment]
You're probably right, I'll check it in the evening again :)

**Comment by mcspr** [comment]
> Yes, I think web UI images should be created for every new feature committed. It's not obvious you have to build them too otherwise.

True. My main problems are diffs and general repo size effects.

While I was writing this, turns out this can be easily solved via .gitattributes to treat them as binary blobs:
```
*.gz.h    -diff -merge
*.gz.h    linguist-generated=true
*.gz.h     -diff -merge
*.gz.h     linguist-generated=true
```

*I would also add a evil check to the CI, comparing generated files to the ones in the commit and fail if they are not the same*


ref:
https://help.github.com/en/articles/customizing-how-changed-files-appear-on-github
https://git-scm.com/docs/gitattributes#_marking_files_as_binary

**Comment by reaper7** [comment]
it was a problem with missing correct webui :) mea culpa !
tnx!

**Comment by schweini** [comment]
I am still missing the MQTT web interface.

i just did a `git pull` and the web interface says i'm running ESPURNA 1.13.4-dev .
I'm using the library `async-mqtt-client-master` from the .zip linked to on the wiki page.

the relevant parts from my custom.h are:

```
#define MQTT_ENABLED                1               // Do not enable MQTT connection by default
#define MQTT_USE_JSON               1               // Group messages in a JSON body
#define MQTT_SERVER                 "XXXXXXX"
#define MQTT_USER                   "XXXXXXX"              // Default MQTT broker usename
#define MQTT_PASS                   "XXXXXXXX"              // Default MQTT broker password
#define MQTT_USE_ASYNC              1           // Use AysncMQTTClient (1) or PubSubClient (0)

```
I have also tried using MQTT_USE_ASYNC 0, but no change.
